//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to the server failed..
        /// </summary>
        internal static string CLN_ALERT_ERROR {
            get {
                return ResourceManager.GetString("CLN_ALERT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your infomation is sent.
        /// </summary>
        internal static string CLN_ALERT_SUCCESS {
            get {
                return ResourceManager.GetString("CLN_ALERT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string CLN_BTN_RESER {
            get {
                return ResourceManager.GetString("CLN_BTN_RESER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string CLN_BTN_SUBMIT {
            get {
                return ResourceManager.GetString("CLN_BTN_SUBMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/about-us.
        /// </summary>
        internal static string CLN_MASTER_ABOUT_US_LINK {
            get {
                return ResourceManager.GetString("CLN_MASTER_ABOUT_US_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        internal static string CLN_MASTER_ABOUT_US_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_ABOUT_US_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/accommodation.
        /// </summary>
        internal static string CLN_MASTER_ACCOMMODATION_LINK {
            get {
                return ResourceManager.GetString("CLN_MASTER_ACCOMMODATION_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation.
        /// </summary>
        internal static string CLN_MASTER_ACCOMMODATION_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_ACCOMMODATION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/booking.
        /// </summary>
        internal static string CLN_MASTER_BOOKING_LINK {
            get {
                return ResourceManager.GetString("CLN_MASTER_BOOKING_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/contact-us.
        /// </summary>
        internal static string CLN_MASTER_CONTACT_US_LINK {
            get {
                return ResourceManager.GetString("CLN_MASTER_CONTACT_US_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        internal static string CLN_MASTER_CONTACT_US_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_CONTACT_US_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/destinations.
        /// </summary>
        internal static string CLN_MASTER_DESTINATIONS_LINK {
            get {
                return ResourceManager.GetString("CLN_MASTER_DESTINATIONS_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/faq.
        /// </summary>
        internal static string CLN_MASTER_FAQ_LINK {
            get {
                return ResourceManager.GetString("CLN_MASTER_FAQ_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        internal static string CLN_MASTER_FAQ_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_FAQ_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a hotel.
        /// </summary>
        internal static string CLN_MASTER_FIND_A_HOTEL_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_FIND_A_HOTEL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/gallery.
        /// </summary>
        internal static string CLN_MASTER_GALLERY_LINK {
            get {
                return ResourceManager.GetString("CLN_MASTER_GALLERY_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        internal static string CLN_MASTER_GALLERY_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_GALLERY_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string CLN_MASTER_HOME {
            get {
                return ResourceManager.GetString("CLN_MASTER_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/index.
        /// </summary>
        internal static string CLN_MASTER_HOMEPAGE_LINK {
            get {
                return ResourceManager.GetString("CLN_MASTER_HOMEPAGE_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asian Ruby Luxury.
        /// </summary>
        internal static string CLN_MASTER_HOTEL_1_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_HOTEL_1_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asian Ruby Park View.
        /// </summary>
        internal static string CLN_MASTER_HOTEL_2_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_HOTEL_2_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asian Ruby Central.
        /// </summary>
        internal static string CLN_MASTER_HOTEL_3_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_HOTEL_3_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayflower.
        /// </summary>
        internal static string CLN_MASTER_HOTEL_4_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_HOTEL_4_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/privacy-policy.
        /// </summary>
        internal static string CLN_MASTER_POLICY_LINK {
            get {
                return ResourceManager.GetString("CLN_MASTER_POLICY_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string CLN_MASTER_POLICY_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_POLICY_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/promotion.
        /// </summary>
        internal static string CLN_MASTER_PROMOTION_LINK {
            get {
                return ResourceManager.GetString("CLN_MASTER_PROMOTION_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion.
        /// </summary>
        internal static string CLN_MASTER_PROMOTION_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_PROMOTION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Now.
        /// </summary>
        internal static string CLN_MASTER_RESERVATION_BUTTON {
            get {
                return ResourceManager.GetString("CLN_MASTER_RESERVATION_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The best rooms and suites avaliable.
        /// </summary>
        internal static string CLN_MASTER_RESERVATION_DES {
            get {
                return ResourceManager.GetString("CLN_MASTER_RESERVATION_DES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/reservation.
        /// </summary>
        internal static string CLN_MASTER_RESERVATION_LINK {
            get {
                return ResourceManager.GetString("CLN_MASTER_RESERVATION_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Your Stay.
        /// </summary>
        internal static string CLN_MASTER_RESERVATION_MOBI_BUTTON {
            get {
                return ResourceManager.GetString("CLN_MASTER_RESERVATION_MOBI_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        internal static string CLN_MASTER_RESERVATION_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_RESERVATION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/services.
        /// </summary>
        internal static string CLN_MASTER_SERVICES_LINK {
            get {
                return ResourceManager.GetString("CLN_MASTER_SERVICES_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string CLN_MASTER_SERVICES_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_SERVICES_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/term-and-condition.
        /// </summary>
        internal static string CLN_MASTER_TERM_LINK {
            get {
                return ResourceManager.GetString("CLN_MASTER_TERM_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term and Condition.
        /// </summary>
        internal static string CLN_MASTER_TERM_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_TERM_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local time.
        /// </summary>
        internal static string CLN_MASTER_TIME {
            get {
                return ResourceManager.GetString("CLN_MASTER_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/tours.
        /// </summary>
        internal static string CLN_MASTER_TOURS_LINK {
            get {
                return ResourceManager.GetString("CLN_MASTER_TOURS_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tours.
        /// </summary>
        internal static string CLN_MASTER_TOURS_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_TOURS_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local temp.
        /// </summary>
        internal static string CLN_MASTER_WEATHER {
            get {
                return ResourceManager.GetString("CLN_MASTER_WEATHER", resourceCulture);
            }
        }
    }
}
