//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1026
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "10.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Strings", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting to the server failed..
        /// </summary>
        internal static string CLN_ALERT_ERROR {
            get {
                return ResourceManager.GetString("CLN_ALERT_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your infomation is sent.
        /// </summary>
        internal static string CLN_ALERT_SUCCESS {
            get {
                return ResourceManager.GetString("CLN_ALERT_SUCCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        internal static string CLN_BOOKING_CALENDAR_AVAILABLE {
            get {
                return ResourceManager.GetString("CLN_BOOKING_CALENDAR_AVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select your dates from the calendar.
        /// </summary>
        internal static string CLN_BOOKING_CALENDAR_NOTICE {
            get {
                return ResourceManager.GetString("CLN_BOOKING_CALENDAR_NOTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected Dates.
        /// </summary>
        internal static string CLN_BOOKING_CALENDAR_SELECTED_DATE {
            get {
                return ResourceManager.GetString("CLN_BOOKING_CALENDAR_SELECTED_DATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unavailable.
        /// </summary>
        internal static string CLN_BOOKING_CALENDAR_UNAVAILABLE {
            get {
                return ResourceManager.GetString("CLN_BOOKING_CALENDAR_UNAVAILABLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Availability.
        /// </summary>
        internal static string CLN_BOOKING_CHECK_AVAILABILITY {
            get {
                return ResourceManager.GetString("CLN_BOOKING_CHECK_AVAILABILITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check In.
        /// </summary>
        internal static string CLN_BOOKING_CHECK_IN {
            get {
                return ResourceManager.GetString("CLN_BOOKING_CHECK_IN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check Out.
        /// </summary>
        internal static string CLN_BOOKING_CHECK_OUT {
            get {
                return ResourceManager.GetString("CLN_BOOKING_CHECK_OUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Reservation.
        /// </summary>
        internal static string CLN_BOOKING_EDIT_RESERVATION {
            get {
                return ResourceManager.GetString("CLN_BOOKING_EDIT_RESERVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please do not reload the page.
        /// </summary>
        internal static string CLN_BOOKING_FAIL_NOTES {
            get {
                return ResourceManager.GetString("CLN_BOOKING_FAIL_NOTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to begin your booking here.
        /// </summary>
        internal static string CLN_BOOKING_FAIL_REDIRECT {
            get {
                return ResourceManager.GetString("CLN_BOOKING_FAIL_REDIRECT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address *.
        /// </summary>
        internal static string CLN_BOOKING_FORM_ADDRESS {
            get {
                return ResourceManager.GetString("CLN_BOOKING_FORM_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Now.
        /// </summary>
        internal static string CLN_BOOKING_FORM_BOOK_NOW {
            get {
                return ResourceManager.GetString("CLN_BOOKING_FORM_BOOK_NOW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City *.
        /// </summary>
        internal static string CLN_BOOKING_FORM_CITY {
            get {
                return ResourceManager.GetString("CLN_BOOKING_FORM_CITY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Country *.
        /// </summary>
        internal static string CLN_BOOKING_FORM_COUNTRY {
            get {
                return ResourceManager.GetString("CLN_BOOKING_FORM_COUNTRY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address *.
        /// </summary>
        internal static string CLN_BOOKING_FORM_EMAIL {
            get {
                return ResourceManager.GetString("CLN_BOOKING_FORM_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name *.
        /// </summary>
        internal static string CLN_BOOKING_FORM_FIRST_NAME {
            get {
                return ResourceManager.GetString("CLN_BOOKING_FORM_FIRST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Guest Details.
        /// </summary>
        internal static string CLN_BOOKING_FORM_GUEST_DETAIL {
            get {
                return ResourceManager.GetString("CLN_BOOKING_FORM_GUEST_DETAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name *.
        /// </summary>
        internal static string CLN_BOOKING_FORM_LAST_NAME {
            get {
                return ResourceManager.GetString("CLN_BOOKING_FORM_LAST_NAME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special Requirements.
        /// </summary>
        internal static string CLN_BOOKING_FORM_NOTES {
            get {
                return ResourceManager.GetString("CLN_BOOKING_FORM_NOTES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill out the required fields marked with *.
        /// </summary>
        internal static string CLN_BOOKING_FORM_NOTICE {
            get {
                return ResourceManager.GetString("CLN_BOOKING_FORM_NOTICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State / County *.
        /// </summary>
        internal static string CLN_BOOKING_FORM_STATE_COUNTY {
            get {
                return ResourceManager.GetString("CLN_BOOKING_FORM_STATE_COUNTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone Number *.
        /// </summary>
        internal static string CLN_BOOKING_FORM_TELEPHONE {
            get {
                return ResourceManager.GetString("CLN_BOOKING_FORM_TELEPHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string CLN_BOOKING_FROM {
            get {
                return ResourceManager.GetString("CLN_BOOKING_FROM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Night.
        /// </summary>
        internal static string CLN_BOOKING_NIGHT {
            get {
                return ResourceManager.GetString("CLN_BOOKING_NIGHT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occupancy.
        /// </summary>
        internal static string CLN_BOOKING_OCCUPANCY {
            get {
                return ResourceManager.GetString("CLN_BOOKING_OCCUPANCY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Person(s).
        /// </summary>
        internal static string CLN_BOOKING_PERSONS {
            get {
                return ResourceManager.GetString("CLN_BOOKING_PERSONS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airport pick up.
        /// </summary>
        internal static string CLN_BOOKING_PICKUP {
            get {
                return ResourceManager.GetString("CLN_BOOKING_PICKUP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation Complete.
        /// </summary>
        internal static string CLN_BOOKING_RESERVATION_COMPLETE {
            get {
                return ResourceManager.GetString("CLN_BOOKING_RESERVATION_COMPLETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        internal static string CLN_BOOKING_RESERVATION_COMPLETE_ADDRESS {
            get {
                return ResourceManager.GetString("CLN_BOOKING_RESERVATION_COMPLETE_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string CLN_BOOKING_RESERVATION_COMPLETE_EMAIL {
            get {
                return ResourceManager.GetString("CLN_BOOKING_RESERVATION_COMPLETE_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details of your reservation have just been sent to you in a confirmation email,
        ///                                we look forward to seeing you soon. In the meantime if you have any questions feel
        ///                                free to contact us..
        /// </summary>
        internal static string CLN_BOOKING_RESERVATION_COMPLETE_INFO {
            get {
                return ResourceManager.GetString("CLN_BOOKING_RESERVATION_COMPLETE_INFO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone.
        /// </summary>
        internal static string CLN_BOOKING_RESERVATION_COMPLETE_PHONE {
            get {
                return ResourceManager.GetString("CLN_BOOKING_RESERVATION_COMPLETE_PHONE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Room.
        /// </summary>
        internal static string CLN_BOOKING_ROOM {
            get {
                return ResourceManager.GetString("CLN_BOOKING_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rooms.
        /// </summary>
        internal static string CLN_BOOKING_ROOMS {
            get {
                return ResourceManager.GetString("CLN_BOOKING_ROOMS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Airport see off.
        /// </summary>
        internal static string CLN_BOOKING_SEEOFF {
            get {
                return ResourceManager.GetString("CLN_BOOKING_SEEOFF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select room.
        /// </summary>
        internal static string CLN_BOOKING_SELECT_ROOM {
            get {
                return ResourceManager.GetString("CLN_BOOKING_SELECT_ROOM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Your Date.
        /// </summary>
        internal static string CLN_BOOKING_STEP_1 {
            get {
                return ResourceManager.GetString("CLN_BOOKING_STEP_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Choose Your Room.
        /// </summary>
        internal static string CLN_BOOKING_STEP_2 {
            get {
                return ResourceManager.GetString("CLN_BOOKING_STEP_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place Your Reservation.
        /// </summary>
        internal static string CLN_BOOKING_STEP_3 {
            get {
                return ResourceManager.GetString("CLN_BOOKING_STEP_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirmation.
        /// </summary>
        internal static string CLN_BOOKING_STEP_4 {
            get {
                return ResourceManager.GetString("CLN_BOOKING_STEP_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Price.
        /// </summary>
        internal static string CLN_BOOKING_TOTAL_PRICE {
            get {
                return ResourceManager.GetString("CLN_BOOKING_TOTAL_PRICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Reservation.
        /// </summary>
        internal static string CLN_BOOKING_YOUR_RESERVATION {
            get {
                return ResourceManager.GetString("CLN_BOOKING_YOUR_RESERVATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string CLN_BTN_RESER {
            get {
                return ResourceManager.GetString("CLN_BTN_RESER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string CLN_BTN_SUBMIT {
            get {
                return ResourceManager.GetString("CLN_BTN_SUBMIT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Our location.
        /// </summary>
        internal static string CLN_INDEX_LOCATION {
            get {
                return ResourceManager.GetString("CLN_INDEX_LOCATION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More+.
        /// </summary>
        internal static string CLN_INDEX_READMORE {
            get {
                return ResourceManager.GetString("CLN_INDEX_READMORE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special deal.
        /// </summary>
        internal static string CLN_INDEX_SPECIAL_DEAL {
            get {
                return ResourceManager.GetString("CLN_INDEX_SPECIAL_DEAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tours.
        /// </summary>
        internal static string CLN_INDEX_TOUR {
            get {
                return ResourceManager.GetString("CLN_INDEX_TOUR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/about-us.
        /// </summary>
        internal static string CLN_MASTER_ABOUT_US_LINK {
            get {
                return ResourceManager.GetString("CLN_MASTER_ABOUT_US_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About us.
        /// </summary>
        internal static string CLN_MASTER_ABOUT_US_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_ABOUT_US_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/accommodation.
        /// </summary>
        internal static string CLN_MASTER_ACCOMMODATION_LINK {
            get {
                return ResourceManager.GetString("CLN_MASTER_ACCOMMODATION_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accommodation.
        /// </summary>
        internal static string CLN_MASTER_ACCOMMODATION_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_ACCOMMODATION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/booking-step-1.
        /// </summary>
        internal static string CLN_MASTER_BOOKING_LINK {
            get {
                return ResourceManager.GetString("CLN_MASTER_BOOKING_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/contact-us.
        /// </summary>
        internal static string CLN_MASTER_CONTACT_US_LINK {
            get {
                return ResourceManager.GetString("CLN_MASTER_CONTACT_US_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contact us.
        /// </summary>
        internal static string CLN_MASTER_CONTACT_US_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_CONTACT_US_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/destinations.
        /// </summary>
        internal static string CLN_MASTER_DESTINATIONS_LINK {
            get {
                return ResourceManager.GetString("CLN_MASTER_DESTINATIONS_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/faq.
        /// </summary>
        internal static string CLN_MASTER_FAQ_LINK {
            get {
                return ResourceManager.GetString("CLN_MASTER_FAQ_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FAQ.
        /// </summary>
        internal static string CLN_MASTER_FAQ_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_FAQ_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find a hotel.
        /// </summary>
        internal static string CLN_MASTER_FIND_A_HOTEL_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_FIND_A_HOTEL_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/gallery.
        /// </summary>
        internal static string CLN_MASTER_GALLERY_LINK {
            get {
                return ResourceManager.GetString("CLN_MASTER_GALLERY_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gallery.
        /// </summary>
        internal static string CLN_MASTER_GALLERY_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_GALLERY_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string CLN_MASTER_HOME {
            get {
                return ResourceManager.GetString("CLN_MASTER_HOME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/index.
        /// </summary>
        internal static string CLN_MASTER_HOMEPAGE_LINK {
            get {
                return ResourceManager.GetString("CLN_MASTER_HOMEPAGE_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asian Ruby Luxury.
        /// </summary>
        internal static string CLN_MASTER_HOTEL_1_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_HOTEL_1_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asian Ruby Park View.
        /// </summary>
        internal static string CLN_MASTER_HOTEL_2_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_HOTEL_2_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asian Ruby Central.
        /// </summary>
        internal static string CLN_MASTER_HOTEL_3_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_HOTEL_3_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mayflower.
        /// </summary>
        internal static string CLN_MASTER_HOTEL_4_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_HOTEL_4_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/privacy-policy.
        /// </summary>
        internal static string CLN_MASTER_POLICY_LINK {
            get {
                return ResourceManager.GetString("CLN_MASTER_POLICY_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        internal static string CLN_MASTER_POLICY_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_POLICY_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/promotion.
        /// </summary>
        internal static string CLN_MASTER_PROMOTION_LINK {
            get {
                return ResourceManager.GetString("CLN_MASTER_PROMOTION_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Promotion.
        /// </summary>
        internal static string CLN_MASTER_PROMOTION_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_PROMOTION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Now.
        /// </summary>
        internal static string CLN_MASTER_RESERVATION_BUTTON {
            get {
                return ResourceManager.GetString("CLN_MASTER_RESERVATION_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The best rooms and suites avaliable.
        /// </summary>
        internal static string CLN_MASTER_RESERVATION_DES {
            get {
                return ResourceManager.GetString("CLN_MASTER_RESERVATION_DES", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book Your Stay.
        /// </summary>
        internal static string CLN_MASTER_RESERVATION_MOBI_BUTTON {
            get {
                return ResourceManager.GetString("CLN_MASTER_RESERVATION_MOBI_BUTTON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reservation.
        /// </summary>
        internal static string CLN_MASTER_RESERVATION_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_RESERVATION_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/services.
        /// </summary>
        internal static string CLN_MASTER_SERVICES_LINK {
            get {
                return ResourceManager.GetString("CLN_MASTER_SERVICES_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string CLN_MASTER_SERVICES_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_SERVICES_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/term-and-condition.
        /// </summary>
        internal static string CLN_MASTER_TERM_LINK {
            get {
                return ResourceManager.GetString("CLN_MASTER_TERM_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Term and Condition.
        /// </summary>
        internal static string CLN_MASTER_TERM_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_TERM_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local time.
        /// </summary>
        internal static string CLN_MASTER_TIME {
            get {
                return ResourceManager.GetString("CLN_MASTER_TIME", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /en/tours.
        /// </summary>
        internal static string CLN_MASTER_TOURS_LINK {
            get {
                return ResourceManager.GetString("CLN_MASTER_TOURS_LINK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tours.
        /// </summary>
        internal static string CLN_MASTER_TOURS_TEXT {
            get {
                return ResourceManager.GetString("CLN_MASTER_TOURS_TEXT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local temp.
        /// </summary>
        internal static string CLN_MASTER_WEATHER {
            get {
                return ResourceManager.GetString("CLN_MASTER_WEATHER", resourceCulture);
            }
        }
    }
}
